<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ELearningManagementSystem.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.14" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ELearningManagementSystem.Application\ELearningManagementSystem.Application.csproj" />
    <ProjectReference Include="..\ELearningManagementSystem.Domain\ELearningManagementSystem.Domain.csproj" />
    <ProjectReference Include="..\ELearningManagementSystem.Shared\ELearningManagementSystem.Shared.csproj" />
  </ItemGroup>

</Project>
